name: django-allow-cidr PyPI release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  pre_release_checks:
    runs-on: ubuntu-latest
    name: django-allow-cidr Pre-Release CI checks
    steps:
      - name: Run CI checks again before publishing package
        uses: ./.github/workflows/ci

  release:
    runs-on: ubuntu-latest
    name: django-allow-cidr Release
    needs:
      - pre_release_checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies for package building only
        run: pip install build
      - name: Build package for upload to PyPI
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
          .
      - name: Upload the distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
